#!/bin/bash
clear
#--------------------------
# SSH-PLUS SCRIPT
# TELEGRAM CHANNEL: @
#--------------------------

# - Colors
RED='\033[1;31m'
YELLOW='\033[1;33m'
SCOLOR='\033[0m'

# - Check for Root Execution
[[ "$EUID" -ne 0 ]] && {
    echo -e "${RED}[x] YOU NEED TO RUN AS ROOT USER!${SCOLOR}"
    exit 1
}

# - Check Compatible Architecture
case "$(uname -m)" in
    'amd64' | 'x86_64')
        arch='64'
        ;;
    'aarch64' | 'armv8')
        arch='arm64'
        ;;
    *)
        echo -e "${RED}[x] INCOMPATIBLE ARCHITECTURE!${SCOLOR}"
        exit 1
        ;;
esac

# - Check Compatible OS
if grep -qs "ubuntu" /etc/os-release; then
	os_version=$(grep 'VERSION_ID' /etc/os-release | cut -d '"' -f 2 | tr -d '.')
    [[ "$os_version" -lt 1804 ]] && {
        echo -e "${RED}[x] INCOMPATIBLE UBUNTU VERSION!\n${YELLOW}[!] REQUIRES UBUNTU 18.04 OR HIGHER!${SCOLOR}"
        exit 1
    }
elif [[ -e /etc/debian_version ]]; then
	os_version=$(grep -oE '[0-9]+' /etc/debian_version | head -1)
    [[ "$os_version" -lt 9 ]] && {
        echo -e "${RED}[x] INCOMPATIBLE DEBIAN VERSION!\n${YELLOW}[!] REQUIRES DEBIAN 9 OR HIGHER!${SCOLOR}"
        exit 1
    }
else
    echo -e "${RED}[x] INCOMPATIBLE OS!\n${YELLOW}[!] REQUIRES DEBIAN/UBUNTU BASED DISTROS!${SCOLOR}"
    exit 1
fi

# - Update Package Lists/Packages/System
dpkg --configure -a
apt update -y && apt upgrade -y
apt install unzip python3 -y

# - Disable IPv6
sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -p
echo 'net.ipv6.conf.all.disable_ipv6 = 1' > /etc/sysctl.d/70-disable-ipv6.conf
sysctl -p -f /etc/sysctl.d/70-disable-ipv6.conf

# - Execute Installer
[[ -e Plus ]] && rm Plus
wget raw.githubusercontent.com/JeanRocha91x/SSHPLUS/main/script/${arch}/Plus && chmod 777 Plus && ./Plus
